# Development Docker Compose configuration with hot-reload
services:
  postgres:
    image: postgres:16-alpine
    container_name: dota-stats-postgres-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: dota-stats-rabbitmq-dev
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dota-stats-backend-dev
    env_file:
      - .env
    environment:
      - DEBUG=true
    ports:
      - "8282:8000"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./logs/backend:/app/logs
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dota-stats-celery-worker-dev
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./logs/celery-worker:/app/logs
    command: celery -A app.tasks.celery_app worker --loglevel=debug --logfile=/app/logs/error.log

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dota-stats-celery-beat-dev
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./logs/celery-beat:/app/logs
    command: celery -A app.tasks.celery_app beat --loglevel=debug --logfile=/app/logs/error.log

  # Flower (Celery Monitoring)
  flower:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dota-stats-flower-dev
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./logs/flower:/app/logs
    command: celery -A app.tasks.celery_app flower --port=5555 --logging=error --log-file-prefix=/app/logs/error.log

  # Frontend with Vite dev server
  frontend:
    image: node:20-alpine
    container_name: dota-stats-frontend-dev
    working_dir: /app
    ports:
      - "8383:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development

volumes:
  postgres_data_dev:
